name: CI-PR
on:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm run build
      - working-directory: core
        run: |
          npm run bundle
          npm run bundle:min

      - run: npm run coverage
      - run: npm run doc